name: Run tests on test branch

on:
  push:
    branches:
      - test01
  pull_request:
    branches:
      - test01
      

jobs:
  test:
    runs-on: windows-latest
    
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
      
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Visual Studio Build Tools
        uses: microsoft/setup-msbuild@v1.0.2
      
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        with:
          nuget-version: 5.x
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install pm2
        run: npm install pm2 -g

      - name: Start WinAppDriver with pm2
        run: pm2 start "D:/a/freelancing2/freelancing2/WinAppDriver_baseDirectory/WinAppDriver.exe" --name "WinAppDriver"
        
      - name: Restore dependencies
        run: nuget restore ./WebUITestAutomation.sln
        
      - name: Restore dotnet dependencies
        run: dotnet restore ./WebUITestAutomation.sln
        
      - name: Build
        run: dotnet build ./WebUITestAutomation.sln --no-restore
        
      - name: Get IP address
        run: ipconfig.exe
        
#       - name: Download and extract Windows Application Driver
#         shell: powershell
#         run: |
#           Invoke-WebRequest "https://github.com/microsoft/WinAppDriver/releases/tag/v1.2.1/WindowsApplicationDriver_1.2.1.msi" -OutFile "$env:TEMP\WindowsApplicationDriver.msi"
#           Start-Process msiexec.exe -ArgumentList '/i', "$env:TEMP\WindowsApplicationDriver_1.2.1.msi", '/quiet', '/norestart' -NoNewWindow -Wait
#         run: Start-Process -FilePath "D:/a/freelancing2/freelancing2/WinAppDriver_baseDirectory/WinAppDriver.exe" -ArgumentList "--port", "4723", "--url-base", "/wd/hub" -NoNewWindow -RedirectStandardOutput winappdriver.log
#         run: Start-Process -FilePath "D:/a/freelancing2/freelancing2/WinAppDriver_baseDirectory/WinAppDriver.exe" -NoNewWindow -Wait
#         run: D:/a/freelancing2/freelancing2/WinAppDriver_baseDirectory/WinAppDriver.exe 4723
#         run: Start-Process 'cmd' -ArgumentList '/c "D:/a/freelancing2/freelancing2/WinAppDriver_baseDirectory/WinAppDriver.exe" 1>winappdriver_out.log'
        
#       - name: Run Test
#         run: D:/a/freelancing2/freelancing2/WinAppDriver_baseDirectory/WinAppDriver.exe 4723
        
      - name: Run tests
        run: dotnet test "D:\a\freelancing2\freelancing2\bin\Debug\UnitTestProject1.dll" --no-build --verbosity normal --logger "trx;LogFileName=testresults.trx"
      
      - name: Upload TRX result files
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: "./TestResults/testresults.trx"
        if: ${{ always() }}
      
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: test-results
          path: "./TestResults/testresults.trx"
        if: ${{ always() }}
      
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          trx_files: "./TestResults/testresults.trx"
